### PR TITLE
Only add CFI instructions for panic=unwind build

### LINKED ISSUE #39: Regression: `error: this directive must appear between .cfi_startproc and .cfi_endproc directives`
I recently started getting failures when doing builds with basic projects using `eyra` which internally brings in `unwinding`.

The errors initially were lacking information about the crate producing the error but I've identified it's a recent change to `unwinding`.

When using nightly to build with `-Z build-std=std,panic_abort` paired with `-C panic=abort` I am getting this failure:

```bash
cargo init /tmp/example && cd /tmp/example
cargo add unwinding

# Add `extern crate unwinding;` to `src/main.rs`, then build:
RUSTFLAGS='-C panic=abort -C target-feature=+crt-static' cargo +nightly build \
  --release \
  --target x86_64-unknown-linux-gnu \
  -Z build-std=std,panic_abort
```

```rust
   Compiling unwinding v0.2.3
error: this directive must appear between .cfi_startproc and .cfi_endproc directives
  --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/unwinding-0.2.3/src/unwinder/arch/x86_64.rs:66:13
   |
66 |             .cfi_def_cfa_offset 0xA0
   |             ^
   |
note: instantiated into assembly here
  --> <inline asm>:4:13
   |
4  |             .cfi_def_cfa_offset 0xA0
   |             ^

error: this directive must appear between .cfi_startproc and .cfi_endproc directives
  --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/unwinding-0.2.3/src/unwinder/arch/x86_64.rs:90:13
   |
90 |             .cfi_def_cfa_offset 8
   |             ^
   |
note: instantiated into assembly here
  --> <inline asm>:28:13
   |
28 |             .cfi_def_cfa_offset 8
   |             ^
```

---

The failure cause when used indirectly via `eyra` seemed to not trigger provided I didn't have `-C panic=abort` or did not do `-Z build-std` (_which requires `=std,panic_abort` if abort is set_).

However with `unwinding` directly I noticed that it would fail like above with only `-C panic=abort` present:

```bash
# Failure as above:
RUSTFLAGS='-C panic=abort' cargo +nightly build --release --target x86_64-unknown-linux-gnu
RUSTFLAGS='-C panic=abort' cargo +nightly build --release --target x86_64-unknown-linux-gnu -Z build-std=std,panic_abort

# Without `-C panic=abort`, this works as expected:
cargo +nightly build --release --target x86_64-unknown-linux-gnu
cargo +nightly build --release --target x86_64-unknown-linux-gnu -Z build-std=std,panic_abort

# With the `panic-handler` feature enabled, same error as above:
cargo add unwinding --features panic-handler
# Previously this would fail for duplicate lang item (panic_impl):
RUSTFLAGS='-C panic=abort' cargo +nightly build --release --target x86_64-unknown-linux-gnu
RUSTFLAGS='-C panic=abort' cargo +nightly build --release --target x86_64-unknown-linux-gnu -Z build-std=std,panic_abort
# Failure duplicate lang item (panic_impl), as expected due to std use:
cargo +nightly build --release --target x86_64-unknown-linux-gnu
```

---

Previously it working with `unwinding=0.2.2` on nightly before the `naked_asm` failure was introduced [which `0.2.3` fixed](https://github.com/nbdd0121/unwinding/issues/38) and presumably introduced this regression?:

```toml
[toolchain]
profile = "minimal"
channel = "nightly-2024-10-04"
components = ["rust-src"]
targets = ["x86_64-unknown-linux-gnu"]
```

The prior cargo commands for the `0.2.2` release on that nightly all avoid the reported error.

### PR DESCRIPTION
**Pull request by nbdd0121**
Fix #39

CFI directives are omitted when panic=abort is used.

### CODE REVIEW

**Comment by nbdd0121** [comment]
@bjorn3 @sunfishcode would you mind doing a quick review? Thanks!

**Review by sunfishcode — APPROVED** [review]
This looks good, thanks! I was worried fixing this would require duplicating a bunch of code, but this macro approach looks reasonable. I can also confirm that this works in the Eyra build.

**Review by bjorn3 — APPROVED** [review]
I was thinking if LTO could cause problems when unwinding is compiled as panic=unwind and the executable as panic=abort, but then I remembered that we no longer make all functions panic=abort when doing LTO when any crate is panic=abort to handle `extern "C-unwind"` safely.

**Comment by pantsman0** [comment]
Is there a planned release intended to include this merge? I'm using this crate for implementation of panic catching in an embedded system thread implementation, but this requires passing `-C panic=unwind` and enabling symbols on release builds.

**Comment by nbdd0121** [comment]
Published 0.2.4

**Pull request merged**
